variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  # Minu konteineri registri aadress AWS-s (Amazon Elastic Container Registry)
  # Asenda MINU_REGISTRI_NIMI
  DOCKER_REGISTRY: 662032419283.dkr.ecr.eu-north-1.amazonaws.com/contracts

stages:
  - build
  - api_test

build:back-end:
  image:
    name: docker:27.3.1-alpine3.20
  services:
    - docker:27.3.1-alpine3.20
  only:
    - master
    - main
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install --break-system-packages awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
  script:
    - docker build -t ${DOCKER_REGISTRY}/back:${CI_COMMIT_SHA} ./Backend/API/
    - docker push ${DOCKER_REGISTRY}/back:${CI_COMMIT_SHA}
  after_script:
    - docker logout ${DOCKER_REGISTRY}
  stage: build
  artifacts:
    paths:
  tags:
    - itb2203

build:front-end:
  image:
    name: docker:27.3.1-alpine3.20
  services:
    - docker:27.3.1-alpine3.20
  only:
    - master
    - main
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install --break-system-packages awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
  script:
    - docker build -t ${DOCKER_REGISTRY}/front:${CI_COMMIT_SHA} ./Frontend/
    - docker push ${DOCKER_REGISTRY}/front:${CI_COMMIT_SHA}
  after_script:
    - docker logout ${DOCKER_REGISTRY}
  stage: build
  artifacts:
    paths:
  tags:
    - itb2203

api_test:
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  image:
    name: docker:27.3.1-alpine3.20
    entrypoint: ["/bin/sh", "-c"]
  services:
    - docker:27.3.1-alpine3.20
  only:
    - master
    - main
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install --break-system-packages awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
  script:
    - cd ApiTests
    - docker compose up --abort-on-container-exit --exit-code-from newman
    - docker compose down -v
  after_script:
    - docker logout ${ITB2203_REGISTRY}
  stage: api_test
  tags:
    - itb2203
