services:
  postgres:
    image: postgres:17-alpine
    container_name: api_db
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - pg_net
  back_end:
    image: ${DOCKER_REGISTRY}/back:${CI_COMMIT_SHA}
    container_name: back_end
    environment:
      - ASPNETCORE_URLS=http://+:5143
      - ASPNETCORE_ENVIRONMENT=Testing
    depends_on:
      - postgres
    networks:
      - pg_net
      - api_net
    links:
      - "postgres:db"
    volumes:
      - ./startup:/etc/startup
    entrypoint:
      [
        "/etc/startup/wait-for",
        "-t",
        "30",
        "db:5432",
        "--",
        "dotnet",
        "/app/API.dll",
      ]
  newman:
    image: postman/newman:alpine
    entrypoint:
      ["/etc/startup/wait-for", "-t", "30", "back_end:5143", "--", "newman"]
    container_name: newman
    depends_on:
      - postgres
      - back_end
    network_mode: "service:back_end"
    volumes:
      - ./startup:/etc/startup
      - ./newman/:/etc/newman/
    command: run /etc/newman/Contracts.postman_collection.json -e Contracts.postman_environment.json
networks:
  pg_net:
  api_net:
